# Arquivo para armazenar segredos da aplicação, como a URL do banco de dados.
# O Streamlit carrega este arquivo automaticamente.
DATABASE_URL="postgresql://neondb_owner:npg_t2PSNsZa6iWT@ep-long-cell-ah65sj0l-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
